v0.1.2 (#4)
- bump package version `v0.1.1` -> `v0.1.2`
- bump dependencies
- copy updates: tidy up README, add JSDoc
- deprecate node v16
- improve github action publish workflow

diff --git a/.github/workflows/npm-workflow.yml b/.github/workflows/npm-workflow.yml
--- a/.github/workflows/npm-workflow.yml
+++ b/.github/workflows/npm-workflow.yml
@@ -2,31 +2,41 @@ name: Publish package to npm
 
 on:
   release:
-    types: [created]
+    types: [published]
 
 jobs:
-  build-and-test:
+  ensure-version-match:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 18
-      - run: npm ci
-      - run: npm run build
-      - run: npm test
+      - uses: actions/checkout@v4
 
-  publish-npm:
-    needs: build-and-test
+      # Ensure package.json version matches release tag
+      - name: Verify package version matches release tag
+        run: |
+          RELEASE_TAG=${{ github.event.release.tag_name }}
+          PKG_VERSION=$(node -p "require('./package.json').version")
+          if [ "$RELEASE_TAG" != "v$PKG_VERSION" ]; then
+            echo "Error: Release tag '$RELEASE_TAG' does not match package.json version 'v$PKG_VERSION'"
+            exit 1
+          fi
+  publish:
+    needs: ensure-version-match
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
           registry-url: https://registry.npmjs.org/
       - run: npm ci
       - run: npm run build
-      - run: npm publish
+      - run: npm run test:ci
+      - name: Publish dry-run
+        run: npm publish --dry-run
+      - name: Publish to NPM
+        run: npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
